version: '3'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend
    expose:
      - "5432"
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    build:
      dockerfile: ./docker/Dockerfile.local
      context: .

    
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend
    ports:
      - "3000:3000"
networks: 
  backend:
