FROM node:dubnium-alpine
WORKDIR /app



COPY package.json ./package.json
COPY yarn.lock ./yarn.lock

RUN yarn install


COPY src src
COPY migrations migrations
COPY bin bin
COPY .babelrc .babelrc
COPY nodemon.json nodemon.json

CMD ["yarn", "start:dev"]
