FROM node:dubnium-alpine
WORKDIR /app

RUN apk add --no-cache git

COPY package.json ./package.json
COPY yarn.lock ./yarn.lock

RUN yarn install

COPY .git .git
COPY src src
COPY migrations migrations
COPY bin bin
COPY .babelrc .babelrc


CMD ["yarn", "test:dev", "--watch"]
